/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2022-05-27 17:06:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1650642727490L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1648980334511L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648557165838L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1648557162089L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1632897780223L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t<body class=\"no-skin\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"main-content\">\r\n");
      out.write("\t\t\t\t<div class=\"main-content-inner\">\r\n");
      out.write("\t\t\t\t\t<div class=\"breadcrumbs\" id=\"breadcrumbs\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-home home-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/quan-tri/trang-chu\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul><!-- /.breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nav-search\" id=\"nav-search\">\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"form-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search ...\" class=\"nav-search-input\" id=\"nav-search-input\" autocomplete=\"off\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-search nav-search-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- /.nav-search -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"page-content\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- PAGE CONTENT BEGINS -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("\t                                <div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"widget-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-header widget-header-flat widget-header-small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-signal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tThể loại và sản phẩm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h5>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-toolbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-action=\"collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"piechart-placeholder-product\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hr hr8 hr-double\"></div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-main -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-body -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-box -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><!-- /.col -->\r\n");
      out.write("                                  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"vspace-12-sm\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"widget-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-header widget-header-flat widget-header-small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h5 class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-signal\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tNgười dùng và quản lý\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</h5>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-toolbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" data-action=\"collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"ace-icon fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"widget-main\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"piechart-placeholder-user\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hr hr8 hr-double\"></div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-main -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-body -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div><!-- /.widget-box -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div><!-- /.col -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div><!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"hr hr32 hr-dotted\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div><!-- /.page-content -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- /.main-content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#\" id=\"btn-scroll-up\" class=\"btn-scroll-up btn btn-sm btn-inverse\">\r\n");
      out.write("\t\t\t\t<i class=\"ace-icon fa fa-angle-double-up icon-only bigger-110\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t<!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if IE]>\r\n");
      out.write("<script src=\"assets/js/jquery.1.11.1.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if !IE]> -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\twindow.jQuery || document.write(\"<script src='assets/js/jquery.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if IE]>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" window.jQuery || document.write(\"<script src='assets/js/jquery1x.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tif('ontouchstart' in document.documentElement) document.write(\"<script src='assets/js/jquery.mobile.custom.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- page specific plugin scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--[if lte IE 8]>\r\n");
      out.write("\t\t  <script src=\"assets/js/excanvas.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t\t<script src=\"assets/js/jquery-ui.custom.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/jquery.flot.resize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ace scripts -->\r\n");
      out.write("\t\t<script src=\"assets/js/ace-elements.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/ace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- inline scripts related to this page -->\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(function($) {\r\n");
      out.write("\t\t\t\t$('.easy-pie-chart.percentage').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = $(this).data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');\r\n");
      out.write("\t\t\t\t\tvar trackColor = barColor == 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';\r\n");
      out.write("\t\t\t\t\tvar size = parseInt($(this).data('size')) || 50;\r\n");
      out.write("\t\t\t\t\t$(this).easyPieChart({\r\n");
      out.write("\t\t\t\t\t\tbarColor: barColor,\r\n");
      out.write("\t\t\t\t\t\ttrackColor: trackColor,\r\n");
      out.write("\t\t\t\t\t\tscaleColor: false,\r\n");
      out.write("\t\t\t\t\t\tlineCap: 'butt',\r\n");
      out.write("\t\t\t\t\t\tlineWidth: parseInt(size/10),\r\n");
      out.write("\t\t\t\t\t\tanimate: /msie\\s*(8|7|6)/.test(navigator.userAgent.toLowerCase()) ? false : 1000,\r\n");
      out.write("\t\t\t\t\t\tsize: size\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.sparkline').each(function(){\r\n");
      out.write("\t\t\t\t\tvar $box = $(this).closest('.infobox');\r\n");
      out.write("\t\t\t\t\tvar barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';\r\n");
      out.write("\t\t\t\t\t$(this).sparkline('html',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttagValuesAttribute:'data-values',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype: 'bar',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbarColor: barColor ,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchartRangeMin:$(this).data('min') || 0\r\n");
      out.write("\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //flot chart resize plugin, somehow manipulates default browser resize event to optimize it!\r\n");
      out.write("\t\t\t  //but sometimes it brings up errors with normal resize event handlers\r\n");
      out.write("\t\t\t  $.resize.throttleWindow = false;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  /* Sản phẩm\t */\t\r\n");
      out.write("\t\t\t  var placeholder = $('#piechart-placeholder-product').css({'width':'90%' , 'min-height':'150px'});\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    var productXuongKhop = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.productXuongKhop}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\t\tvar productDaiTrang = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.productDaiTrang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\tvar productNao = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.productNao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t  var data = [\t\t\t\t\r\n");
      out.write("\t\t\t\t{ label: \"Xương khớp\",  data: productXuongKhop, color: \"#2091CF\"},\t\t\t\r\n");
      out.write("\t\t\t\t{ label: \"Đại tràng\",  data: productDaiTrang, color: \"#DA5430\"},\r\n");
      out.write("\t\t\t\t{ label: \"Não\",  data: productNao, color: \"#FEE074\"}\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t\t\t  function drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t \t  $.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tpie: {\r\n");
      out.write("\t\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt:0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight: {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity: 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke: {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor: '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth: 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle: 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend: {\r\n");
      out.write("\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\tposition: position || \"ne\", \r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor: null,\r\n");
      out.write("\t\t\t\t\t\tmargin:[-30,15]\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\t\tclickable: true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t drawPieChart(placeholder, data);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t /**\r\n");
      out.write("\t\t\t we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\t so that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t placeholder.data('chart', data);\r\n");
      out.write("\t\t\t placeholder.data('draw', drawPieChart);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t\t  //pie chart tooltip example\r\n");
      out.write("\t\t\t  var $tooltip = $(\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\").hide().appendTo('body');\r\n");
      out.write("\t\t\t  var previousPoint = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  placeholder.on('plothover', function (event, pos, item) {\r\n");
      out.write("\t\t\t\tif(item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \" + item.series['percent']+'%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({top:pos.pageY + 10, left:pos.pageX + 10});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \t\t\t  \t\t\t  \t\t\t  \r\n");
      out.write("\t\t\t  /* Người dùng\t */\t\t\t\t  \t\t\t  \t\t\t  \r\n");
      out.write("\t\t\t  var placeholder = $('#piechart-placeholder-user').css({'width':'90%' , 'min-height':'150px'});\t\r\n");
      out.write("\t\t\t  \t\t\t   \r\n");
      out.write("\t\t\t\tvar userAdmin = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.userAdmin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\tvar userManager = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.userManager}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\tvar userStaff = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.userStaff}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\tvar userUser = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.userUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("\t\t\t\tvar userUserIncognito = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model.userUserIncognito}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  var data = [\r\n");
      out.write("\t\t\t\t{ label: \"Giám đốc\",  data: userAdmin, color: \"#68BC31\"},\r\n");
      out.write("\t\t\t\t{ label: \"Trưởng phòng\",  data: userManager, color: \"#2091CF\"},\r\n");
      out.write("\t\t\t\t{ label: \"Nhân viên\",  data: userStaff, color: \"#AF4E96\"}, \r\n");
      out.write("\t\t\t\t{ label: \"Người dùng\",  data: userUser, color: \"#DA5430\"},\r\n");
      out.write("\t\t\t\t{ label: \"Người đăng kí\",  data: userUserIncognito, color: \"#FEE074\"}\r\n");
      out.write("\t\t\t  ]\r\n");
      out.write("\t\t\t  function drawPieChart(placeholder, data, position) {\r\n");
      out.write("\t\t\t \t  $.plot(placeholder, data, {\r\n");
      out.write("\t\t\t\t\tseries: {\r\n");
      out.write("\t\t\t\t\t\tpie: {\r\n");
      out.write("\t\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\t\ttilt:0.8,\r\n");
      out.write("\t\t\t\t\t\t\thighlight: {\r\n");
      out.write("\t\t\t\t\t\t\t\topacity: 0.25\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstroke: {\r\n");
      out.write("\t\t\t\t\t\t\t\tcolor: '#fff',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth: 2\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tstartAngle: 2\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tlegend: {\r\n");
      out.write("\t\t\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\t\t\tposition: position || \"ne\", \r\n");
      out.write("\t\t\t\t\t\tlabelBoxBorderColor: null,\r\n");
      out.write("\t\t\t\t\t\tmargin:[-30,15]\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\tgrid: {\r\n");
      out.write("\t\t\t\t\t\thoverable: true,\r\n");
      out.write("\t\t\t\t\t\tclickable: true\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t drawPieChart(placeholder, data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t /**\r\n");
      out.write("\t\t\t we saved the drawing function and the data to redraw with different position later when switching to RTL mode dynamically\r\n");
      out.write("\t\t\t so that's not needed actually.\r\n");
      out.write("\t\t\t */\r\n");
      out.write("\t\t\t placeholder.data('chart', data);\r\n");
      out.write("\t\t\t placeholder.data('draw', drawPieChart);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  //pie chart tooltip example\r\n");
      out.write("\t\t\t  var $tooltip = $(\"<div class='tooltip top in'><div class='tooltip-inner'></div></div>\").hide().appendTo('body');\r\n");
      out.write("\t\t\t  var previousPoint = null;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  placeholder.on('plothover', function (event, pos, item) {\r\n");
      out.write("\t\t\t\tif(item) {\r\n");
      out.write("\t\t\t\t\tif (previousPoint != item.seriesIndex) {\r\n");
      out.write("\t\t\t\t\t\tpreviousPoint = item.seriesIndex;\r\n");
      out.write("\t\t\t\t\t\tvar tip = item.series['label'] + \" : \" + item.series['percent']+'%';\r\n");
      out.write("\t\t\t\t\t\t$tooltip.show().children(0).text(tip);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$tooltip.css({top:pos.pageY + 10, left:pos.pageX + 10});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$tooltip.hide();\r\n");
      out.write("\t\t\t\t\tpreviousPoint = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t/////////////////////////////////////\r\n");
      out.write("\t\t\t\t$(document).one('ajaxloadstart.page', function(e) {\r\n");
      out.write("\t\t\t\t\t$tooltip.remove();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#recent-box [data-rel=\"tooltip\"]').tooltip({placement: tooltip_placement});\r\n");
      out.write("\t\t\t\tfunction tooltip_placement(context, source) {\r\n");
      out.write("\t\t\t\t\tvar $source = $(source);\r\n");
      out.write("\t\t\t\t\tvar $parent = $source.closest('.tab-content')\r\n");
      out.write("\t\t\t\t\tvar off1 = $parent.offset();\r\n");
      out.write("\t\t\t\t\tvar w1 = $parent.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar off2 = $source.offset();\r\n");
      out.write("\t\t\t\t\t//var w2 = $source.width();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tif( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';\r\n");
      out.write("\t\t\t\t\treturn 'left';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('.dialogs,.comments').ace_scroll({\r\n");
      out.write("\t\t\t\t\tsize: 300\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//Android's default browser somehow is confused when tapping on label which will lead to dragging the task\r\n");
      out.write("\t\t\t\t//so disable dragging when clicking on label\r\n");
      out.write("\t\t\t\tvar agent = navigator.userAgent.toLowerCase();\r\n");
      out.write("\t\t\t\tif(\"ontouchstart\" in document && /applewebkit/.test(agent) && /android/.test(agent))\r\n");
      out.write("\t\t\t\t  $('#tasks').on('touchstart', function(e){\r\n");
      out.write("\t\t\t\t\tvar li = $(e.target).closest('#tasks li');\r\n");
      out.write("\t\t\t\t\tif(li.length == 0)return;\r\n");
      out.write("\t\t\t\t\tvar label = li.find('label.inline').get(0);\r\n");
      out.write("\t\t\t\t\tif(label == e.target || $.contains(label, e.target)) e.stopImmediatePropagation() ;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#tasks').sortable({\r\n");
      out.write("\t\t\t\t\topacity:0.8,\r\n");
      out.write("\t\t\t\t\trevert:true,\r\n");
      out.write("\t\t\t\t\tforceHelperSize:true,\r\n");
      out.write("\t\t\t\t\tplaceholder: 'draggable-placeholder',\r\n");
      out.write("\t\t\t\t\tforcePlaceholderSize:true,\r\n");
      out.write("\t\t\t\t\ttolerance:'pointer',\r\n");
      out.write("\t\t\t\t\tstop: function( event, ui ) {\r\n");
      out.write("\t\t\t\t\t\t//just for Chrome!!!! so that dropdowns on items don't appear below other items after being moved\r\n");
      out.write("\t\t\t\t\t\t$(ui.item).css('z-index', 'auto');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t\t\t$('#tasks').disableSelection();\r\n");
      out.write("\t\t\t\t$('#tasks input:checkbox').removeAttr('checked').on('click', function(){\r\n");
      out.write("\t\t\t\t\tif(this.checked) $(this).closest('li').addClass('selected');\r\n");
      out.write("\t\t\t\t\telse $(this).closest('li').removeClass('selected');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//show the dropdowns on top or bottom depending on window height and menu position\r\n");
      out.write("\t\t\t\t$('#task-tab .dropdown-hover').on('mouseenter', function(e) {\r\n");
      out.write("\t\t\t\t\tvar offset = $(this).offset();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\tvar $w = $(window)\r\n");
      out.write("\t\t\t\t\tif (offset.top > $w.scrollTop() + $w.innerHeight() - 100) \r\n");
      out.write("\t\t\t\t\t\t$(this).addClass('dropup');\r\n");
      out.write("\t\t\t\t\telse $(this).removeClass('dropup');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/admin/home.jsp(30,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.accessDenied != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t               <div class=\"alert alert-danger\">\t\r\n");
          out.write("\t\t\t\t\t\t\t       Bạn không có quyền vào trang này\r\n");
          out.write("\t\t\t\t\t               </div>\r\n");
          out.write("\t\t\t\t      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
