/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2022-05-05 16:37:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1650642727490L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1648980334511L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648557165838L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1648557162089L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1632897780223L));
    _jspx_dependants.put("jar:file:/D:/Back%20End/Spring-MVC-test/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-ban-hang/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Thái minh</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"banner\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <img src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- body-->\r\n");
      out.write("       <div class=\"container my-3\">\r\n");
      out.write("         <img class=\"my-3\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" width=\"300px\" alt=\"\">\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("           <div>\r\n");
      out.write("            <h2>Thái Minh</h2>\r\n");
      out.write("            <div class=\"row my-3\">\r\n");
      out.write("                <div class=\"col-md-9 \">\r\n");
      out.write("                    <p>Công ty Cổ phần Dược phẩm Thái Minh chính thức đi vào hoạt động ngày 15/2/2012, với trụ sở được đăng ký tại Số 1C, tổ 36, cụm 5, Xuân La, Tây Hồ, Hà Nội, văn phòng đặt tại P605, chung cư Nhân Mỹ, ngõ 52 Phạm Hùng, Từ Liêm, Hà Nội, với 12 nhân viên ban đầu (kể cả chính thức và dự bị).</p>\r\n");
      out.write("                    <p>Nhờ sự hỗ trợ, giúp đỡ ngay từ những ngày đầu của các đối tác như công ty IMC, công ty Viễn Bằng, công ty LOHHA, Thái Minh đang từng bước trưởng thành và lớn mạnh không ngừng. Doanh số liên tục tăng trưởng, thị phần được mở rộng, chỉ với 03 sản phẩm tính đến thời điểm tháng 12/2013 là Tràng Phục Linh, Maxxhair và Tràng Phục Linh Plus, Thái Minh cùng các đối tác của mình đã phát triển được hệ thống phân phối sâu và rộng trên cả nước, với hơn 2500 điểm bán đều là khách hàng thân thiết. Ba sản phẩm của Thái Minh được khách hàng nhà thuốc và người tiêu dùng tin tưởng, đánh giá cao về hiệu quả điều trị và hỗ trợ điều trị các bệnh viêm đại tràng, rụng tóc, hội chứng ruột kích thích. Đó chính là cơ sở để Thái Minh tự tin tiếp tục phát triển thêm các sản phẩm mới trong năm 2014 và đầu tư phát triển hệ thống phân phối mạnh mẽ, sâu rộng và có chất lượng hơn trong những năm sau…</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 \">\r\n");
      out.write("                    <img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" width=\"250px\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>            \r\n");
      out.write("          </div>    \r\n");
      out.write("          \r\n");
      out.write("         <div> \r\n");
      out.write("            <h3>Lịch sử phát triển</h3>\r\n");
      out.write("            <div class=\"row my-3\">\r\n");
      out.write("                <div class=\"col-md-3 \">          \r\n");
      out.write("                    <img  src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" width=\"250px\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-9 \">\r\n");
      out.write("                    <p>Tiền thân của Thái Minh là Phòng Marketing trực thuộc công ty TNHH Tư vấn Y Dược Quốc tế (IMC).Trưởng phòng – ThS.DS. Nguyễn Quang Thái – là Chủ tịch công ty Thái Minh hiện nay, vốn là Lưu học sinh của trường ĐH Dược Hà Nội cử sang LB Nga theo học tại Học viện Hóa dược Xanh – Petecbua.  Anh cùng phòng Marketing của IMC chính là những người lên ý tưởng, phát triển sản phẩm và làm thị trường cho các nhãn hàng Tràng Phục Linh, Maxxhair từ khi còn là dự án đến lúc chính thức được chuyển sang thành sản phẩm hợp tác giữa Thái Minh – IMC và LOHHA .</p>\r\n");
      out.write("                    <p>Ấp ủ ý tưởng thay đổi thói quen tiêu dùng của người Việt Nam trong ngành Dược từ các sản phẩm nhập ngoại sang các sản phẩm của Việt Nam, dựa trên những sản phẩm có chất lượng vượt trội, được nghiên cứu kỹ lưỡng, được làm Marketing một cách chuyên nghiệp và được bán rộng rãi trên thị trường, công ty Thái Minh được thành lập để trở thành nơi hội tụ những yếu tố cốt lõi trên.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("            <h3>Sứ mệnh – Tầm nhìn</h3>\r\n");
      out.write("            <div class=\"row my-5\">\r\n");
      out.write("                <div class=\"col-md-9 \">\r\n");
      out.write("                    <p>Sứ mệnh: “Giúp giải quyết những vấn đề sức khoẻ con người mà thế giới còn đang chưa có giải pháp tối ưu dựa trên tinh hoa của khoa học và thảo dược, ghi dấu ấn Việt Nam trên bản đồ Y học thế giới”</p>\r\n");
      out.write("                    <p>Công ty Cổ phần Dược phẩm Thái Minh chính thức đi vào hoạt động ngày 15/2/2012, với 12 nhân viên ban đầu (kể cả chính thức và dự bị). Thái Minh thể hiện cho ánh sáng mạnh mẽ của mặt trời, của hy vọng, với mong ước mỗi khi bệnh nhân nhìn thấy logo trên các sản phẩm của Thái Minh là thêm một lần được tiếp thêm hy vọng trong cuộc chiến chống lại bệnh tật và gia tăng chất lượng cuộc sống.</p>\r\n");
      out.write("                    <p>Nhờ sự nỗ lực và tinh thần học hỏi sáng tạo không ngừng, Thái Minh đã từng bước trưởng thành và lớn mạnh. Doanh số liên tục tăng trưởng, thị phần được mở rộng. Hiện tại Thái Minh đã phát triển được trên 10 sản phẩm trong top đầu thị trường, xây dựng được hệ thống phân phối chuyên nghiệp trên cả nước với 10.000 điểm bán khắp các tỉnh thành.</p>\r\n");
      out.write("                    <p>Năm 2019, Thái Minh đã khai trương nhà máy Thái Minh Công nghệ cao ( ThaiMinh HiTech), sản xuất  TPCN, mỹ phẩm đạt chuẩn GMP tại KCN Quốc Oai, với công suất 30 triệu viên/tháng.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 \">              \r\n");
      out.write("                    <img  src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" width=\"250px\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/about.jsp(15,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/web/images/banner9.jpg");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/about.jsp(20,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/web/images/logo3.png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/web/about.jsp(31,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/web/images/gt1.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/web/about.jsp(40,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/web/images/gt4.png");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/web/about.jsp(60,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/template/web/images/gt2.png");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }
}
